import React from 'react'
import { GraphQLClient, gql } from 'graphql-request';
import Header from '@/components/Header'
import MainPage from '@/components/MainPage';
import Head from 'next/head'

function index({posts}) {
  return (
    <>
      <Head>
        <title>Savvy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="cont">
        <Header />
        <main className='xl:w-[80%] bg-transparent xl:mx-auto mt-14 h-[78vh] mb-8'>
          <MainPage posts={posts} />
        </main>
      </div>
    </>
  )
}

export default index


export async function getStaticProps() {
    const hygraph = new GraphQLClient(
      `${process.env.HYGRAPH_ENDPOINT}`
    );
  
    const QUERY = gql`
    query Assets {
      posts {
        slug
        id
        image {
          url
        }
        metaDescription
        dateCreated
        featured
        title
      }
    }
    `
    const { posts } = await hygraph.request(QUERY);
    posts.reverse();
    return {
      props: {
        posts
      },
      revalidate: 60
    }
  }